services:
  mysql:
    image: 'mysql:9'
    environment:
      - 'MYSQL_DATABASE=backbase'
      - 'MYSQL_PASSWORD=backbase_pwd'
      - 'MYSQL_ROOT_PASSWORD=root_pwd'
      - 'MYSQL_USER=backbase'
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
